-- TURN ON YOUR MYSQL WORKBENCH --> OPEN ONE LOCALHOST SERVER 
-- PASTE AND RUN THIS SCRIPT TO CREATE DATABASE
CREATE DATABASE latedeliverydb CHARACTER SET UTF8MB4;
CREATE USER 'user123'@'localhost' IDENTIFIED BY 'password123';
GRANT ALL PRIVILEGES ON latedeliverydb.* TO 'user123'@'localhost';
FLUSH PRIVILEGES;