# Generated by Django 4.2.24 on 2025-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('trainer', 'Trainer')], default='user', max_length=20),
        ),
    ]
