# Generated by Django 4.2.25 on 2025-11-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMachineLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('customer_state', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=100)),
                ('order_country', models.CharField(max_length=100)),
                ('order_region', models.CharField(max_length=100)),
                ('order_state', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('customer_city', models.CharField(max_length=100)),
                ('order_city', models.CharField(max_length=100)),
                ('shipping_mode', models.CharField(max_length=100)),
                ('days_for_shipment_scheduled', models.FloatField()),
                ('order_item_discount_rate', models.FloatField()),
                ('order_item_product_price', models.FloatField()),
                ('order_item_quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('sales_per_customer', models.FloatField(blank=True, null=True)),
                ('benefit_per_order', models.FloatField(blank=True, null=True)),
                ('order_item_profit_ratio', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('late_delivery_risk', models.BooleanField(blank=True, null=True)),
                ('model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.mlmodel')),
            ],
        ),
    ]
