# Generated by Django 4.2.25 on 2025-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_mlmodel_ordermachinelearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermachinelearning',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermachinelearning',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
