# Generated by Django 4.2.26 on 2025-11-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermachinelearning_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_state', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.CharField(blank=True, max_length=100, null=True)),
                ('order_country', models.CharField(blank=True, max_length=100, null=True)),
                ('order_region', models.CharField(blank=True, max_length=100, null=True)),
                ('order_state', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_city', models.CharField(blank=True, max_length=100, null=True)),
                ('order_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('days_for_shipment_scheduled', models.IntegerField()),
                ('benefit_per_order', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sales_per_customer', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('order_item_discount_rate', models.FloatField(blank=True, null=True)),
                ('order_item_product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('order_item_profit_ratio', models.FloatField(blank=True, null=True)),
                ('order_item_quantity', models.IntegerField(blank=True, null=True)),
                ('late_delivery_risk', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order for ML',
                'verbose_name_plural': 'Orders for ML',
                'db_table': 'order_orderforml',
                'ordering': ['-id'],
            },
        ),
    ]
